### ISSUE TITLE
Write-Error if any Tests fail - Causes GH Action to be marked as failed 

### ISSUE THREAD

**Issue by sofbkeller** [maester365/maester#204]
`Tests Passed ✅: 43, Failed ❌: 71, Skipped ⚫: 7

Write-Error: Status = Failed: See Maester Test Report below for details.
Error: Error: The process '/usr/bin/pwsh' failed with exit code 1`

If any tests fail and the Maester script is run in a Github Action, write-error causes the execution to be marked as a failure. 

I am not sure if this should be specifically fixed because it works as intended but it causes the job to appear as failed in a GitHub Action. As this is a suggested implementation option it might cause some users to be confused why the job is running fine but failing and providing output if they aren't familiar with GH.

**Comment by simon-barratt-seq** [comment]
I have the same issue. I assumed something was failing. The email from github actions confirms my assumption!

**Comment by sofbkeller** [comment]
@simon-barratt-seq This could be fixed ourselves but I think the source should be modified since there isn't really _a need_ imo to have that writing as an error since you aren't looking for errors but for how your test went. 
If the tests actually failed to execute this would make more sense. Do you agree?

**Comment by merill** [comment]
The typical DevOps convention for automated tests is that all tests should pass and if any one test fails the build should fail so you are notified that something is wrong.

What we are doing here is slightly different so it could be implemented either way.

The original idea was that you would set up Maester so it only runs tests that are relevant for your tenant. The tests that you run everyday should all pass. If any one of them fails (maybe due to a config drift, etc) you would be alerted that it failed.

Now since the whole point of the GitHub action is to send out the mail it could be argued that it is redundant. 

I've seen this issue called out a few times so I'm going to comment out that section in the yaml and call out that it can be uncommented for those who want the build to fail if even one test fails.
