### ISSUE TITLE
Validate mailbox before running tests

### ISSUE THREAD

**Issue by dnsinit** [maester365/maester#533]
Would it be possible to validate pre-requisites for sending report by mail when the -MailRecipient parameter is used? As it is right now it runs all tests and then throws below error message only after it fails to send the mail.

{"error":{"code":"MailboxNotEnabledForRESTAPI","message":"The mailbox is either inactive, soft-deleted, or is
     | hosted on-premise."}}

![image](https://github.com/user-attachments/assets/f2a7b411-5b53-4c18-8ea5-57a6d3dccfba)

**Comment by merill** [comment]
I would flag this as by design.

Folks might not want this to be a breaking issue if the daily automations were not run because the mailbox was not there. The tests would still run succesfully and log the results.

Since we have options to send to Teams, Slack etc.. 

Adding this to the beginning of each run would also impact performance.

For those who need this requirement, you can add the test to check for the mailbox as a previous step before calling Invoke-Maester.

If anyone implements a cmdlet to do this check, we would love to include it as a Test-MtAlertMailbox...
