### ISSUE TITLE
Corrections on findings

### ISSUE THREAD

**Issue by ThoughtContagion** [maester365/maester#60]
Not sure if this in intentional or not, but I've found several instances of failed tests where the configured setting is the recommended setting. I will gather the list of these findings and place them in a comment when I finish reviewing the generated report.
![image](https://github.com/maester365/maester/assets/88730003/1e40d7a7-2dd4-4205-b102-06ecf7e9ab42)

There are also some findings that return a value of `****` where the setting does not exist as its queried in the tenant
![image](https://github.com/maester365/maester/assets/88730003/28cd1006-f6a4-4e7f-a03b-7d7f2a48fb1e)
![image](https://github.com/maester365/maester/assets/88730003/3a95d567-ce40-4f2f-8cdf-f498982948c9)

I'm also unsure what some findings are looking for as they trigger a failed result, but the policies/configurations are there.
For example
![image](https://github.com/maester365/maester/assets/88730003/36fc3051-cef4-4f56-a522-d61766d1eec6)
![image](https://github.com/maester365/maester/assets/88730003/2b2699b6-f127-4ac8-8609-da226cb9db1b)

This looks like a fantastic tool, thank you for all your hard work!

**Comment by ThoughtContagion** [comment]
Additional findings that are marked 'Failed' when the recommended setting is configured:
EIDSCA.AT02: Authentication Method - Temporary Access Pass - One-time.

**Comment by f-bader** [comment]
Thank you @ThoughtContagion we will take a closer look

**Comment by jordan-m-hoff** [comment]
+1
I have experienced these same findings. I ran connected with a Global Admin account.

**Comment by dnsinit** [comment]
Just wanted to fill in with some more findings @f-bader : 
EIDSCA.PR02,03,05,06 show as failed if they haven't been touched (meaning they're undefined/null in Graph, default values are also what's recommended).
![image](https://github.com/maester365/maester/assets/46563545/ce34af3e-20c3-4b26-9804-e6ac42e9386f)

Same applies to EIDSCA.ST08 & EIDSCA.ST09.

Below probably needs to be $testResult = $tenantValue -eq 'True' -or '' since empty string being returned should mean default behaviour (True?) aswell.
![image](https://github.com/maester365/maester/assets/46563545/37883b04-9bfb-4b59-bec2-fdebf2c13659)

**Comment by f-bader** [comment]
@Cloud-Architekt let us discuss how to fix this without manually changing the tests, as they would be overwritten when generated. Maybe there needs to be an adjustment in the original JSON as well as the generator to allow default values

**Comment by f-bader** [comment]
@Cloud-Architekt 
We will implement a check if the recommended value != null and the tenant value == null that the text will reflect this more clearly and will ask the user to manually set the value, since non set values could change depending on what Microsoft decides the current default should be.

**Comment by christiannancy** [comment]
At least for "MS.AAD.1.1: Legacy authentication SHALL be blocked", looking at the code in Test-MtCisaBlockLegacyAuth.ps1, line 29, the test fails (at least on PS 5.1) because `$blockPolicies.Count` doesn't return 1 when there is only one policy. The code that works for me is `$testResult = @($blockPolicies).Count -ge 1`.

**Comment by Snozzberries** [comment]
@christiannancy are you possibly using an older version, that bug should have been resolved in v0.0.131 but is resolved in prerelease.

https://github.com/maester365/maester/commit/23a61562363159e0e86b97f86274475751edbf9f

**Comment by christiannancy** [comment]
> @christiannancy are you possibly using an older version, that bug should have been resolved in v0.0.131 but is resolved in prerelease.
> 
> [23a6156](https://github.com/maester365/maester/commit/23a61562363159e0e86b97f86274475751edbf9f)

Ah, my bad, you are correct.

**Comment by Snozzberries** [comment]
No stress, glad it was an easy answer.
