### ISSUE TITLE
redundant tests? EIDSCA.CP04 and EIDSCA.CR01

### ISSUE THREAD

**Issue by kayasax** [maester365/maester#72]
![image](https://github.com/maester365/maester/assets/1241767/8caf6917-b5fc-4c01-9ae4-84a9acf4d6f9)

**Comment by Cloud-Architekt** [comment]
Thanks for the feedback, @kayasax.

Yes, indeed it seems to be the same configuration even if the Graph endpoint is different. It looks like Microsoft has been implemented the configuration about the status of admin consent approval flow in [adminconsentrequestpolicy](https://learn.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-1.0#properties) and [settingTemplates](https://learn.microsoft.com/en-us/graph/group-directory-settings). I would like to keep the check so that it will be shown in relation to the other checks in the category. Consent settings are partly splitted in the two categories. For example, `ConstrainGroupSpecificConsentToMembersOfGroupId` will be shown only in the "Default Settings - Consent Policy Settings" area and approval flow settings in the "Consent Framework - Admin Consent Request" area. I have updated the check name which fits also to the original display name in Graph and would be slightly different between both checks.

Would this approach works for you?
