### ISSUE TITLE
report not updated after remediating issue

### ISSUE THREAD

**Issue by kayasax** [maester365/maester#74]
It seems the report is not updated after fixing some issue and running invoke-maester few minutes after

**Comment by f-bader** [comment]
We use extensive caching to improve performance. Please run `Clear-MtGraphCache` and see if this fixes the issue for you

**Comment by kayasax** [comment]
Yep that works, thanks. What do you think about adding a -force parameter to invoke-maester so this will be done automatically?

**Comment by f-bader** [comment]
Funny enough @merill had already thought about this and does it every time you call `Invoke-Maester`
So the original error might be related to stale data at some other point.

You can check if this actually happens when you use `-Verbose`. You should see the following message
> Clearing the results cached from Graph API calls in this session

![image](https://github.com/maester365/maester/assets/3834359/0cced047-5273-41b0-b0ec-c48f368c1d85)

https://github.com/maester365/maester/blob/fcd1d8be2118150d251d4e54df9080f5f18e49e5/powershell/public/Invoke-Maester.ps1#L212

**Comment by kayasax** [comment]
I ran another test : I mitigate an issue, ran Clear-MtGraphCache  and the report is not updated. (ran all of this in < 5min).
Confirmed the value is correct if I run the graph query.

**Comment by f-bader** [comment]
Thanks for testing this. I will do a deep dive in the next few days. Already added an extra verbose message to see if it's grabbed from live data or the cache.

But sounds more like a debugger issue 🤔

**Comment by DrPye** [comment]
Just want to add I'm having a similar issue when running this against multiple tenants. 

For me all the reports are correct but its still pulling the tenant name from the cache. So its always the first tenant I run the tests on that end up as the title on all the reports. I too have tried ```Clear-MtGraphCache``` but this doesnt solve my problem. I've dived into the code and it does seem to be related to the cache when using the ```ConvertTo-MtMaesterResult``` cmdlet. 

I have run ```-verbose``` and can see cache should be getting cleared as the provided screenshot from f-bader

I hope this helps, I was going to change the code to allow a -MultiTenant flag on invoke-maester but after finding this issue here, it seems you already have thought of this and im barking up the wrong tree?

**Comment by merill** [comment]
This issue should be fixed in [0.0.125](https://github.com/maester365/maester/releases/tag/0.0.125).

Please update the module to the latest version and try again.
